import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./sobre.css";
import "./login.css";
import "./contato.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
       <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
